# permissions for end users to edit bentodeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bentodeployment-editor-role
rules:
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments/status
  verbs:
  - get
