# permissions for end users to view bentodeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bentodeployment-viewer-role
rules:
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serving.yatai.ai
  resources:
  - bentodeployments/status
  verbs:
  - get
