apiVersion: serving.yatai.ai/v2alpha1
kind: BentoDeployment
metadata:
    name: my-bento-deployment
    namespace: yatai
spec:
    extraPodSpec:
      schedulerName: volcano
    bento: iris-classifier
    ingress:
        enabled: true
    resources:
        limits:
            cpu: "500m"
            memory: "512Mi"
            custom:
              volcano.sh/vgpu-number: "1"
              volcano.sh/vgpu-memory: "20725"
        requests:
            cpu: "250m"
            memory: "128Mi"
            custom:
              volcano.sh/vgpu-number: "1"
              volcano.sh/vgpu-memory: "20725"
    autoscaling:
        maxReplicas: 10
        minReplicas: 2
    runners:
        - name: iris_clf
          resources:
              limits:
                  cpu: "1000m"
                  memory: "1Gi"
                  custom:
                    volcano.sh/vgpu-number: "1"
                    volcano.sh/vgpu-memory: "20725"
              requests:
                  cpu: "500m"
                  memory: "512Mi"
                  custom:
                    volcano.sh/vgpu-number: "1"
                    volcano.sh/vgpu-memory: "20725"
          autoscaling:
              maxReplicas: 4
              minReplicas: 1